---
title: "Cade Abrams's resume"
author: Cade Abrams
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
    css: ['css/custom_resume.css', 'css/styles_html.css',  'resume']
    #css: ['css/custom_resume.css', 'css/styles_pdf.css', 'resume']
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---
```{css, echo=FALSE}
#title h1 {
  text-transform: unset;
}
```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------
- <i class="fa fa-mobile"></i> +1(234)-567-8910
- <i class="fa fa-envelope"></i> cade4420@gmail.com
- <i class="fa fa-github"></i> [github.com/Tcabrams44](https://github.com/Tcabrams44)
- <i class="fa fa-linkedin"></i> [cade-abrams-phd](https://www.linkedin.com/in/cade-abrams-phd)
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------
- R
- Python
- Markdown
- Statistical Analysis
- Data Cleaning
- Data Wrangling
- Version Control
- Experimental Design
- Microsoft Excel

#### Commonly Used Libraries
- **R**  

-  broom $\cdot$ conflicted $\cdot$ dplyr $\cdot$ ggplot2 $\cdot$ Hmisc $\cdot$ lubridate $\cdot$ magrittr $\cdot$ purr $\cdot$ readr $\cdot$ stringr $\cdot$ tibble  

- **Python**  

-  glob $\cdot$ ipywidgets $\cdot$ Matplotlib $\cdot$ NumPy $\cdot$ os $\cdot$ pandas $\cdot$ PsychoPy $\cdot$ random $\cdot$ shutil 

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

**BS in Exercise Science**

- Lander University  
- Aug 2017

**MAT in Physical Education**

- University of South Carolina 
- Aug 2019

**PhD emphasis in Motor Behavior**

- University of South Carolina  
- Dec 2022

- Subspecialties in: **Statistics** and **Cognitive Neuroscience**

Main
================================================================================

Cade Abrams, PhD {#title}
--------------------------------------------------------------------------------

As an accomplished data scientist and researcher, I excel in cleaning, analyzing, and managing data sets to derive technical insights to advance research and inform decisions. My passion lies in solving complex problems by leveraging advanced analytical techniques, including predictive models. Trained as an interdisciplinary scientist and educator, I am skilled in effectively communicating complex results to technical and non-technical audiences.

Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Postdoctoral Research Fellow -- Data Scientist

University of South Carolina

Columbia, South Carolina

Aug 2022 - Present

- Conduct advanced statistical analyses using R, including regression modeling 
and hypothesis testing, to extract meaningful insights for academic manuscripts.
- Apply innovative data processing techniques, enhancing sensitivity to 
developmental changes resulting in effect sizes 3 times larger than traditional 
techniques.
- Collaborate with cross-functional and international teams to conduct 
statistical analyses, optimize data processing, and ensure the success of 
ongoing research projects.
- Manage project workflows effectively on GitHub, streamlining research 
processes through version control and collaborative tools.

### Doctoral Graduate Assistant

University of South Carolina

Columbia, South Carolina

Aug 2019 - Aug 2022

- Collaboratively managed a 4-year project through data collection, 
management, cleaning, and predictive modeling to advance motor skill and
cognitive assessments resulting in 5 publications and 12 presentations.
- Saved 42 manual hours across 8 data collections with custom R functions, 
designed to improve data processing efficiency and reduce data entry errors.
- Developed custom data indices for ROTC yielding actionable insights to 
optimize training, resulting in a 16% increase in ACFT pass rates across 1.5 
years (~135 Cadets in sample).

Select Projects {data-icon=code data-concise=true}
--------------------------------------------------------------------------------
### 3-D Model of Motor and Cognitive Solutions
<i class="fa fa-github"></i> [https://github.com/Tcabrams44/complexity-dual-task-conceptual](https://github.com/Tcabrams44/complexity-dual-task-conceptual)

N/A

Summer 2023

Python code creates 3 visual diagrams, simplifying complex motor-cognitive 
relations for non-technical audiences.

:::concise
- Interdisciplinary Research
- Jupyter Notebook
- Data Visualization
- Creativity
:::

### Beyond Traditional Approaches: Examining the Impact of SKIPping with PAX on Post-Error Slowing in Rural Preschoolers
<i class="fa fa-link"></i> [https://osf.io/jyzpx/?view_only=24a908b0a4c842b2843f43a4a37bfd73](https://osf.io/jyzpx/?view_only=24a908b0a4c842b2843f43a4a37bfd73)

N/A

Spring 2023


Open Science Framework project for statistical analysis of cutting-edge data 
processing methods in an academic manuscript.

:::concise
- Quantitative Analysis
- Data Interpretation
- Data Visualization
- Hypothesis Testing
:::

### Custom R Script for Processing and Scoring Army Combat Fitness Test Results
<i class="fa fa-github"></i> [https://github.com/Tcabrams44/ACFT-Custom-Script](https://github.com/Tcabrams44/ACFT-Custom-Script)

N/A

Spring 2021

R functions score raw ACFT event data, including times, accurately and 
efficiently.

:::concise
- Anonymous Functions
- Automation
- Data Wrangling
- Data Processing
:::
