---
title: "Cade Abrams's resume"
author: Cade Abrams
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
    css: ['css/custom_resume.css', 'css/styles_html.css',  'resume']
    #css: ['css/custom_resume.css', 'css/styles_pdf.css', 'resume']
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> cade4420@gmail.com
- <i class="fa fa-github"></i> [github.com/Tcabrams44](https://github.com/Tcabrams44)
- <i class="fa fa-linkedin"></i> [cade-abrams-phd](https://www.linkedin.com/in/cade-abrams-phd)
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------
- R
- Python
- Markdown
- Statistical Analysis
- Data Cleaning
- Data Wrangling
- Version Control

#### Commonly Used Libraries
-  tidyverse $\cdot$ gggplot2 $\cdot$ Hmisc $\cdot$ pandas $\cdot$ NumPy $\cdot$ matplotlib

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

**BS in Exercise Science**

Lander University  
2017

**MAT in Physical Education**

University of South Carolina 
2019

**PhD emphasis in Motor Behavior**

University of South Carolina 
2022

$\cdot$ Subspecialties in: **Statistics** and **Cognitive Neuroscience**

Main
================================================================================

Cade Abrams {#title}
--------------------------------------------------------------------------------

### Summary

I am an experienced researcher and data scientist with expertise in cleaning, analyzing, and managing datasets and translating technical knowledge to guide upper management decision making.

I am passionate about solving problems and delivering insights through leveraging analytical techniques - such as building predictive models. Trained as an interdisciplinary scientist, I am able to derive meaning from data and deploy robust solutions that inform decisions.

Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Postdoctoral Research Fellow -- Data Scientist

University of South Carolina

Columbia, South Carolina

2022 - Present

- Conducted advanced statistical analyses and data wrangling in R for academic manuscripts.
- Applied innovative data processing techniques, enhancing sensitivity to developmental changes, resulting in 1 peer-reviewed manuscript (in-review) and an international conference presentation.
- Collaborated with cross-functional teams to conduct statistical analyses, optimize data processing, and efficiently manage data for ongoing research projects.
- Managed project workflows on GitHub, optimizing research processes.

### Doctoral Graduate Assistant

University of South Carolina

Columbia, South Carolina

2019 - 2022

- Collaborated on data management, cleaning, and predictive modeling for a 4-year project, resulting in 5 publications and 6 international presentations. 
- Realized a 42-hour time savings across 8 data collections through automated data processing with custom R scripts.
- Developed custom data indices, facilitating actionable insights for ROTC Cadet training programs.

Select Projects {data-icon=code data-concise=true}
--------------------------------------------------------------------------------
### 3-D Model of Motor and Cognitive Solutions
<i class="fa fa-github"></i> [here](https://github.com/Tcabrams44/complexity-dual-task-conceptual)

N/A

2023

:::concise
- Python
- Jupyter Notebook
- Data Visualization
:::

### Beyond Traditional Approaches: Examining the Impact of SKIPping with PAX on Post-Error Slowing in Rural Preschoolers
<i class="fa fa-link"></i> [here](https://osf.io/jyzpx/?view_only=24a908b0a4c842b2843f43a4a37bfd73)

N/A

2023

- This project examined the impacts of an integrated intervention on traditional and contemporary estimates of post-error slowing in rural preschoolers.

:::concise
- R
- Innovative Data Processing Techniques
- Data Visualization
:::

### Custom R Scripts for Processing and Scoring Army Combat Fitness Test Results
<i class="fa fa-github"></i> [here](https://osf.io/jyzpx/?view_only=24a908b0a4c842b2843f43a4a37bfd73)

N/A

2020

- Originally created in 2020, the data associated with this project is confidential
and therefore these customized functions had to be published to GitHub separately.

:::concise
- R
- Innovative Data Processing Techniques
- Data Visualization
:::
