---
name: Cade
surname: Abrams
position: "Postdoctoral Research Fellow"
address: "Department of Educational and Developmental Science"
phone: +1(864)-993-8064
email: "tcabrams@email.sc.edu"
github: "Tcabrams44"
linkedin: "cade-abrams-phd"
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "Fill this in."
output: vitae::twentyseconds
editor_options:
  chunk_output_type: console
  keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(vitae)
library(here)
library(tidyverse)
```

```{r}
exp <- read.csv(here("data", "exp.csv"))
```


# Experience

\medskip

```{r}
exp %>% 
  filter(str_detect(keywords, "data-sci")) %>% 
  arrange(desc(Start)) %>%
  detailed_entries(
    what = Title,
    with = Company,
    when = Dates,
    where = Location,
    why = Description,
    .protect = T
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "PhD -- Motor Behavior", "2019 - 2022", 
  "University of South Carolina", "Columbia, South Carolina",
  
  "MAT -- Physical Education", "2017 - 2019", "University of South Carolina", 
  "Columbia, South Carolina",
  
  "BS -- Exercise Science", "2013 - 2017", "Lander University", 
  "Greenwood, South Carolina",
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```
